### ISSUE TITLE
Spec is horribly borked

### ISSUE THREAD

**Issue by domenic** [w3c/resource-hints#59] opened 2016-05-17 21:50 UTC
https://w3c.github.io/resource-hints/ has large sections that have been put into `<pre>` blocks instead of output correctly.

**Comment by igrigorik** [comment] 2016-05-17 22:42
Hmm, interesting. Pushed a "fix" to make it readable: https://github.com/w3c/resource-hints/commit/bb6a96088ba3e2aa65920c9ad54db2dc73a57c44

I suspect recent changes in https://github.com/w3c/respec/issues/724 might be the cause. /cc @marcoscaceres

**Comment by marcoscaceres** [comment] 2016-05-18 05:24
My bad. Should be all good now.

**Comment by igrigorik** [comment] 2016-05-18 05:31
Reverted. Thanks Marcos! Closing :)

**Closed as completed by igrigorik** 2016-05-18 05:31 UTC
